version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

  net_kai:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.1.0/24

  net_ui:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.2.0/24


  # net_tisbi:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 173.17.3.0/24

  # net_kfu:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 173.17.4.0/24

services:
  kai:
    image: hyperledger/develop-build
    ports:
      - "50051:50051"
      - "20000:20000"
    depends_on:
      - postgres_kai
    tty: true
    environment:
      - IROHA_POSTGRES_HOST=173.17.1.11
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - CCACHE_DIR=/tmp/ccache

    volumes:
      - ../:/opt/iroha
      - ccache-data_kai:/tmp/ccache
    working_dir: /opt/iroha

    networks:
      net_kai:
        ipv4_address: 173.17.1.10
      default:
        ipv4_address: 192.168.0.2


  postgres_kai:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
    networks:
      net_kai:
        ipv4_address: 173.17.1.11

  ui:
    image: hyperledger/iroha-docker
    ports:
      - "50051:50051"
    depends_on:
      - postgres_ui
    tty: true
    networks:
      net_ui:
        ipv4_address: 173.17.2.10
      default:
        ipv4_address: 192.168.0.3

  postgres_ui:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
    networks:
      net_ui:
        ipv4_address: 173.17.2.11

volumes:
  ccache-data_kai:
